// Package tokens implements one-time-token verification for the bolthub
// finalize daemon. Tokens are generated by the bolthub API at deploy time
// using HMAC-SHA256 keyed with the per-node webhook secret. The daemon
// holds the same secret (passed in via cloud-init) and re-derives the HMAC
// to verify; consumed tokens are persisted to a flat file so a token
// cannot be replayed even across daemon restarts.
package tokens

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Verifier validates and consumes one-time finalize tokens.
type Verifier struct {
	secret    []byte
	consumed  map[string]struct{}
	storePath string
	mu        sync.Mutex
	now       func() time.Time
}

// New constructs a Verifier persisting consumed tokens under storePath. If
// the file does not exist yet it will be created on the first consume call.
func New(secret []byte, storePath string) (*Verifier, error) {
	if len(secret) == 0 {
		return nil, errors.New("tokens.New: secret must not be empty")
	}
	if storePath == "" {
		return nil, errors.New("tokens.New: storePath must not be empty")
	}
	v := &Verifier{
		secret:    secret,
		consumed:  map[string]struct{}{},
		storePath: storePath,
		now:       time.Now,
	}
	if err := v.load(); err != nil {
		return nil, fmt.Errorf("tokens.New: load: %w", err)
	}
	return v, nil
}

// SetClock overrides the clock; intended for tests.
func (v *Verifier) SetClock(now func() time.Time) {
	v.mu.Lock()
	defer v.mu.Unlock()
	v.now = now
}

func (v *Verifier) load() error {
	f, err := os.Open(v.storePath)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer f.Close()
	buf := make([]byte, 64*1024)
	for {
		n, err := f.Read(buf)
		if n > 0 {
			lines := strings.Split(string(buf[:n]), "\n")
			for _, line := range lines {
				line = strings.TrimSpace(line)
				if line != "" {
					v.consumed[line] = struct{}{}
				}
			}
		}
		if err != nil {
			break
		}
	}
	return nil
}

// Token format: <action>.<expiresUnix>.<nonce>.<hmacHex>
//
// Example: finalize.1714435200.1f3c.7a4b...
//
// `action` is one of the well-known strings the API uses; the daemon checks
// it against the action it expects for the endpoint that received the token.
// Anything past the third `.` is the HMAC-SHA256 of the first three fields
// joined with `.`, using the shared secret.

// Verify parses the supplied opaque token, ensures it has not expired, that
// the action matches expectedAction, and that the HMAC is valid. The token
// is then marked consumed (atomically appended to disk) so it cannot be
// replayed. Returns an error describing any of those checks if they fail.
func (v *Verifier) Verify(token string, expectedAction string) error {
	if token == "" {
		return errors.New("token: empty")
	}
	parts := strings.SplitN(token, ".", 4)
	if len(parts) != 4 {
		return errors.New("token: malformed (need 4 fields)")
	}
	action := parts[0]
	expiresStr := parts[1]
	nonce := parts[2]
	macHex := parts[3]

	if action != expectedAction {
		return fmt.Errorf("token: action mismatch (got %q want %q)", action, expectedAction)
	}

	expiresUnix, err := strconv.ParseInt(expiresStr, 10, 64)
	if err != nil {
		return fmt.Errorf("token: bad expiry: %w", err)
	}

	v.mu.Lock()
	defer v.mu.Unlock()

	if v.now().Unix() > expiresUnix {
		return errors.New("token: expired")
	}

	if _, seen := v.consumed[token]; seen {
		return errors.New("token: already consumed")
	}

	mac := hmac.New(sha256.New, v.secret)
	mac.Write([]byte(strings.Join([]string{action, expiresStr, nonce}, ".")))
	expected := hex.EncodeToString(mac.Sum(nil))
	if !hmac.Equal([]byte(macHex), []byte(expected)) {
		return errors.New("token: bad signature")
	}

	if err := v.persist(token); err != nil {
		return fmt.Errorf("token: persist: %w", err)
	}
	v.consumed[token] = struct{}{}
	return nil
}

// SignResult builds an HMAC over a daemon -> API result payload using the
// same shared secret. The API verifies this MAC before persisting any
// macaroon material so a malicious actor that only learned the daemon URL
// cannot poison the API's macaroon store.
func (v *Verifier) SignResult(payload []byte) string {
	mac := hmac.New(sha256.New, v.secret)
	mac.Write(payload)
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}

func (v *Verifier) persist(token string) error {
	if err := os.MkdirAll(filepath.Dir(v.storePath), 0o700); err != nil {
		return err
	}
	f, err := os.OpenFile(v.storePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := f.WriteString(token + "\n"); err != nil {
		return err
	}
	return f.Sync()
}
